### ISSUE TITLE
The same number in two Try It boxes

### ISSUE THREAD

**Issue by wilkus27** [Connexions/cnx-recipes#461] opened 2018-07-10 15:13 UTC
Module 3.5
https://devb.cnx.org/contents/tWu56V64@33.86:fCadB1zn@12/35-Venn-Diagrams
![number](https://user-images.githubusercontent.com/40228854/42519406-4b8bf3bc-8464-11e8-9c8d-95179f28ba1d.JPG)

**Comment by openstaxalina** [comment] 2018-07-10 17:02
This does seem like a bug.  @helenemccarron please let me know if you'd like content investigation first.

**Comment by helenemccarron** [comment] 2018-07-10 21:33
@openstaxalina this is actually a feature, not a bug. Try its are designed to use the same number as the example before. This might be specific to Business Statistics that has more than one try it per example. 

![2018-07-10_16-31-32](https://user-images.githubusercontent.com/8514591/42538937-f88b4e88-845e-11e8-9c60-10d5b44a9291.png)

**Comment by openstaxalina** [comment] 2018-07-10 22:16
@helenemccarron thanks you for investigating this!  closing.

**Closed by openstaxalina** 2018-07-10 22:16 UTC
Labels: book:introductory.business.statistics
