### ISSUE TITLE
Biology => Art Connection Questions Collating Figure Link, Not Image.

### ISSUE THREAD

**Issue by Stackblocks** [Connexions/cnx-recipes#425] opened 2018-06-20 15:45 UTC
# Scenario

Art Connection questions are collating with a link to the image instead of the image itself, is this the desired behavior? If not, please correct.

# Reproducibility Details
- **URL / Location**: https://devb.cnx.org/contents/GFy_h8cu@10.120:otIsPXu6@10.120/Answer-Key#fs-id1690230-solution

## Screenshots
![image](https://user-images.githubusercontent.com/12678235/41669234-f7c0f11c-7476-11e8-991e-eb6fdad9dbed.png)
---
![image](https://user-images.githubusercontent.com/12678235/41669240-fbf88c0e-7476-11e8-8182-13ed4449ca90.png)
---
![image](https://user-images.githubusercontent.com/12678235/41669246-0008766a-7477-11e8-9efd-035450c2bcdb.png)

# Environment:

- **Instance**:devb
- **OS**:macOS
- **Browser**: FireFox

**Comment by helenemccarron** [comment] 2018-07-06 19:42
I believe this is working as intended. Below is a screenshot of the PDF behaving the same way. 
![2018-07-06_14-41-54](https://user-images.githubusercontent.com/8514591/42397264-dab714f0-812a-11e8-9532-b7b28dfd5562.png)
cc @openstaxalina

**Comment by openstaxalina** [comment] 2018-07-07 01:11
Confirmed this is acceptable.  This is the behavior in the Answer Key and the EOC content in the PDF.  Closing.

**Closed by openstaxalina** 2018-07-07 01:11 UTC
Labels: book:biology
