### ISSUE TITLE
Lists format

### ISSUE THREAD

**Issue by helenemccarron** [Connexions/cnx-recipes#295] opened 2017-07-13 19:51 UTC
# Scenario
PR  ~https://github.com/Connexions/rhaptos.cnxmlutils/pull/159~ https://github.com/Connexions/rhaptos.cnxmlutils/pull/158 addresses to items below:
- The output for lists is inconsistent. Change lists to display nicely when viewed without CSS.
- ~Bug: when using `data-type="enumerated` in the CXML markup, the list is converted into` div`.  Info below is for bug~

# Reproducibility Details

- **Impact area**: everywhere
- **User**: all of them
- **URL / Location**: look here https://tea.cnx.org/contents/yQ53OWvF@2/How-Economies-Can-Be-Organized but anywhere in macro econ or micro econ, like I said: everywhere
- **How many times were you able to reproduce the issue?** : all the time

## Steps to reproduce:

- Inspect a list in an assessment here https://tea.cnx.org/contents/yQ53OWvF@2/How-Economies-Can-Be-Organized
- They aren't lists, they are divs.

## Screenshots

![2017-07-13_14-48-49](https://user-images.githubusercontent.com/8514591/28184799-69cb0284-67da-11e7-9841-b6150a4e3961.png)

# Environment:

- **Instance**: everywhere
- **OS**: all of them
- **Browser**: all of them

# Impact

- **Severity**: high
- **Frequency of occurrence**: all the time

**Comment by philschatz** [comment] 2017-07-13 21:11
I updated the PR link above because the reason this is occurring is because the `<list>` is inside a `<para>` and that (`<p><ol>...</ol></p>`) is **not** allowed in HTML. So the fix is in an earlier-created PR: https://github.com/Connexions/rhaptos.cnxmlutils/pull/158

**Comment by kerwinso** [comment] 2017-07-18 15:14
@philschatz How do we test the rhaptos.cnxmlutils fix, should we just have DevOps deploy `master` for that repo to the qa server?

**Comment by philschatz** [comment] 2017-07-18 18:48
Hmm, I'm not sure... @reedstrm or @pumazi would know... It looks like it was _almost_ as easy as changing the deploy script https://github.com/Connexions/cnx-deploy/blob/master/environments/dev/files/versions.cfg#L93 but that line is commented out.

It might just _automatically_ happen because of https://github.com/Connexions/cnx-deploy/blob/master/environments/dev/files/archive-requirements.txt#L2 but I'm not too familiar with `requirements.txt` files (it seems like that gets the latest version on `master`)

But once you do get the new version of `rhaptos.cnxmlutils` deployed you will likely need to manually publish a new version of each Page/Module that you want to test (this will eventually be in a migration script so that it occurs right after a deployment)

**Comment by philschatz** [comment] 2017-07-19 19:46
Ross has a script that he will give to ops that will retransform all the content using the _new_ version of `rhaptos.cnxmlutils`

**Comment by kerwinso** [comment] 2017-07-19 20:49
Source markup for the screenshot above: https://legacy-tea.cnx.org/content/m64854/1.2/source

```xml
<title>Test Prep For AP® Courses</title>
 <exercise id="fs-id1168003889060">
  <problem id="fs-id1168004009858">
   <para id="fs-id1168003883317">
An economic system characterized by concentrated power over the production of goods and services is known as (a) ____________.
    <list id="fs-id1168003545003" list-type="enumerated" number-style="lower-alpha">
     <item>market economy</item>
     <item>specialization</item>
     <item>division of labor</item>
     <item>globalization</item>
     <item>command economy</item>
    </list>
   </para>
  </problem>
```

**Comment by philschatz** [comment] 2017-07-20 15:12
Thanks for posting the markup.

This should help with converting the lists on QA: https://github.com/Connexions/devops/wiki/retransforming-CNXML--to-HTML

**Comment by philschatz** [comment] 2017-07-20 18:26
aha! The reason it doesn't work on QA is because https://github.com/Connexions/rhaptos.cnxmlutils/pull/159 has not been merged yet. 

@pumazi is there a way to deploy https://github.com/Connexions/rhaptos.cnxmlutils/pull/159 to QA so they can test before merging? Maybe ops could change https://github.com/Connexions/cnx-deploy/blob/master/environments/dev/files/archive-requirements.txt#L2 to point to the branch?

**Comment by kerwinso** [comment] 2017-07-24 15:22
On Friday (7/21/17), devops re-ran cnx-deploy on the qa server, and then re-ran Ross's retransform script. The rhaptos.cnxmlutils repo appears to be pointing to the correct sha (`5f5a10d4324b085c546748372f4b388075c02eac`).

However, when I go to https://qa.cnx.org/contents/P0QbZjyW@1/How-Economies-Can-Be-Organized to test, I see the list output is still divs:

![image](https://user-images.githubusercontent.com/11298165/28530515-b9932c2e-7059-11e7-92fa-b43fec69c515.png)


@helenemccarron @philschatz Any suggestions?

**Comment by philschatz** [comment] 2017-07-24 16:48
hmm, that is odd. The only thing I can think of is that maybe ross' script did not re-run the transforms.

It seems like https://github.com/Connexions/rhaptos.cnxmlutils/compare/record-version might be necessary to verify that the migration script actually ran. (I would need help from @pumazi to pass the correct sha/version in when the CNXML->HTML script runs so that it can be logged into the HTML file)

**Comment by philschatz** [comment] 2017-07-25 15:55
aha! Ross' script errored... so the transaction aborted... so nothing changed:

```
SQL statement "INSERT INTO module_files   (module_ident, fileid, filename)   VALUES ($1, $2, $3);"
PL/Python function "add_module_file"
psql:retransform_cnxml_html.sql:5: INFO:  produce cnxml->html for module_ident = 101136
CONTEXT:  PL/Python function "add_module_file"
psql:retransform_cnxml_html.sql:5: ERROR:  TypeError: string indices must be integers, not str
CONTEXT:  Traceback (most recent call last):
  PL/Python function "add_module_file", line 3, in <module>
    return add_module_file(plpy, TD)
  PL/Python function "add_module_file", line 727, in add_module_file
  PL/Python function "add_module_file", line 218, in produce_html_for_module
  PL/Python function "add_module_file", line 293, in produce_transformed_file
  PL/Python function "add_module_file", line 254, in resolve_urls
  PL/Python function "add_module_file", line 247, in __call__
  PL/Python function "add_module_file", line 445, in fix_anchor_references
  PL/Python function "add_module_file", line 354, in get_page_ident_hash
  PL/Python function "add_module_file", line 151, in flatten_tree_to_ident_hashes
PL/Python function "add_module_file"
psql:retransform_cnxml_html.sql:6: ERROR:  current transaction is aborted, commands ignored until end of transaction block
ROLLBACK
```

Any ideas why that would happen @pumazi ? (Or /cc someone else that might know). I'll try looking around as well

**Comment by pumazi** [comment] 2017-07-25 16:41
I ran into a similar error on tea. Though, that was due to a module developed by baldwin, which likely means it's a bit ❄️ .

**Comment by pumazi** [comment] 2017-07-25 16:45
The problem module is `m47965/1.2` and it is in fact the very same author. @philschatz, can you look into why this content is somehow different? The full path to the content I think would be something like `/content/m47965/1.2/source`.

**Comment by philschatz** [comment] 2017-07-25 17:11
I _think_ the culprit might be that the URL contains a question mark `<a        href='/content/m34546/latest/?collection=col11207/latest'>` and maybe https://github.com/Connexions/cnx-archive/blob/master/cnxarchive/transforms/resolvers.py#L409 does not handle that case properly?

**Comment by pumazi** [comment] 2017-07-25 17:22
Sounds possible. Let's write a test in cnx-archive's transforms logic for this case.

**Comment by karenc** [comment] 2017-07-25 18:56
`/content/m34546/latest/?collection=col11207/latest` passes the test in cnx-archive... :/

**Comment by philschatz** [comment] 2017-07-25 19:31
hmm, The syntax of the link isn't the problem (cnx-archive correctly parses the `href="..."`). But from the stack trace it seems something in https://github.com/Connexions/cnx-epub/blob/master/cnxepub/models.py#L147 (`flatten_tree_to_ident_hashes`) causes  the error `TypeError: string indices must be integers, not str` .  I don't see the args  that are being passed in so I'm at a bit of a loss...

**Comment by philschatz** [comment] 2017-07-25 20:01
aha! I wonder if this is the culprit: https://github.com/Connexions/cnx-archive/blob/master/cnxarchive/transforms/resolvers.py#L355:

```
if isinstance(tree, basestring):
    tree = json.loads(tree)
```

This is not covered in the unit tests and my python is rusty but maybe this would need to be something like:

```
if isinstance(tree, basestring):
    tree = json.loads(tree)
    # This error-checking could also go into https://github.com/Connexions/cnx-epub/blob/master/cnxepub/models.py#L147
    if isinstance(tree, str):
        throw Error("Whoops! Expected an object")
    if not ('contents' in tree or 'id' in tree):
        throw Error("Whoops! Expected something but got {tree}")
```

**Comment by karenc** [comment] 2017-07-25 21:01
Maybe tree_to_json.sql is returning an empty string:

```
karen@qa00:~$ psql -U rhaptos repository -c "SELECT tree_to_json('d394d2b3-8ce0-4182-9631-18cf68be920c', '18.6', TRUE)"
 tree_to_json 
--------------
 
(1 row)

karen@qa00:~$ psql -U rhaptos repository -c "SELECT tree_to_json('d394d2b3-8ce0-4182-9631-18cf68be920c', '18.6', FALSE)"
                                                                  tree_to_json                                                                   
-------------------------------------------------------------------------------------------------------------------------------------------------
 {"id":"d394d2b3-8ce0-4182-9631-18cf68be920c@18.6","shortId":"05TSs4zg@18.6","title":"Introduction to XML", "contents":[                        +
     {"id":"subcol","shortId":"subcol","title":"Preface", "contents":[                                                                          +
         {"id":"28fbff54-eeca-4a9d-87fd-e3c1661e4daf@2","shortId":"KPv_VO7K@2","title":"Preface, Introduction to XML"}]},                       +
     {"id":"subcol","shortId":"subcol","title":"ITSE1356", "contents":[                                                                         +
         {"id":"8e1cc59a-71f5-455f-a778-312de12c440f@5","shortId":"jhzFmnH1@5","title":"A Brief Introduction to XML"},                          +
         {"id":"e0924b81-ea1c-42a8-823d-2b2aebf864e0@5","shortId":"4JJLgeoc@5","title":"XML - Tags, Elements, Content, and Attributes"},        +
         {"id":"d8c4a5bc-1a60-483c-8aba-5f634570ca25@8","shortId":"2MSlvBpg@8","title":"XML - Well-Formed and Valid Documents"},                +
         {"id":"999d07f7-47d9-42ad-bba7-e8837faf19f0@4","shortId":"mZ0H90fZ@4","title":"Xml0100 Writing XML Review"},                           +
         {"id":"5f200dfa-c590-4d97-8d27-e50dc761ec04@2","shortId":"XyAN-sWQ@2","title":"Xml0110 Transforming XML Review"},                      +
         {"id":"130bae60-ef72-4fcf-a313-4844f703c8f4@2","shortId":"EwuuYO9y@2","title":"Xml0120 Validating XML Review"},                        +
         {"id":"aaf7da27-4a94-4fef-a5d1-65b094eb82ae@1","shortId":"qvfaJ0qU@1","title":"Json0110: Preface to JSON"},                            +
         {"id":"497498bd-cf29-4662-9c01-0815f36c8ccb@1","shortId":"SXSYvc8p@1","title":"Json0120: What is JSON?"},                              +
         {"id":"3432a6de-ed5b-49df-b6f5-f4717f6f2faa@6","shortId":"NDKm3u1b@6","title":"Json0130: JSON and JavaScript"},                        +
         {"id":"208099c2-2175-4927-a50e-59d3d3bf7fcc@1","shortId":"IICZwiF1@1","title":"Json0140-Calling External JavaScript Functions"}]},     +
     {"id":"subcol","shortId":"subcol","title":"Flex", "contents":[                                                                             +
         {"id":"a783d6c7-2674-4425-be32-5f788a927ec1@1","shortId":"p4PWxyZ0@1","title":"XML - Namespaces - Flex 3"},                            +
         {"id":"f9aca92e-f01c-4e71-bdbf-249e34880ca8@1","shortId":"-aypLvAc@1","title":"XML - Namespaces - Flex 4"},                            +
         {"id":"ecffe202-d6c2-4bf0-9a9a-6045dc65fd0e@2","shortId":"7P_iAtbC@2","title":"The Default Application Container - Flex 3 and Flex 4"},+
         {"id":"693a6f0a-5b8c-4bcd-9e2d-0b979c697d3d@1","shortId":"aTpvCluM@1","title":"Using Flex 3 in a Flex 4 World"},                       +
         {"id":"a9375fd0-5b84-49a2-b83c-db226e008140@1","shortId":"qTdf0FuE@1","title":"Handling Slider Change Events in Flex 3 and Flex 4"},   +
         {"id":"1b75e7ce-22e5-4807-9ea4-63a074865f36@2","shortId":"G3XnziLl@2","title":"Flex Resources"}]}]}
(1 row)
```

**Comment by pumazi** [comment] 2017-07-25 21:10
I don't think it's an empty string. It's either returning json or null. The casting (`::json`) in the query will ensure that the results are really json parseable.

Since this explicitly calls for the non-baked tree. A null value won't be returned. And even it it were that would be a different error.

**Comment by philschatz** [comment] 2017-07-25 21:13
So, the answer seems to be that "The tree is empty if 'collated' is TRUE" - @karenc .

<details>
<summary>Click to see Log</summary>

```
karen@qa00:~$ psql -U rhaptos repository -c "SELECT tree_to_json('d394d2b3-8ce0-4182-9631-18cf68be920c', '18.6', TRUE)"
 tree_to_json 
--------------
 
(1 row)

karen@qa00:~$ psql -U rhaptos repository -c "SELECT tree_to_json('d394d2b3-8ce0-4182-9631-18cf68be920c', '18.6', FALSE)"
                                                                  tree_to_json                                                                   
-------------------------------------------------------------------------------------------------------------------------------------------------
 {"id":"d394d2b3-8ce0-4182-9631-18cf68be920c@18.6","shortId":"05TSs4zg@18.6","title":"Introduction to XML", "contents":[                        +
     {"id":"subcol","shortId":"subcol","title":"Preface", "contents":[                                                                          +
         {"id":"28fbff54-eeca-4a9d-87fd-e3c1661e4daf@2","shortId":"KPv_VO7K@2","title":"Preface, Introduction to XML"}]},                       +
     {"id":"subcol","shortId":"subcol","title":"ITSE1356", "contents":[                                                                         +
         {"id":"8e1cc59a-71f5-455f-a778-312de12c440f@5","shortId":"jhzFmnH1@5","title":"A Brief Introduction to XML"},                          +
         {"id":"e0924b81-ea1c-42a8-823d-2b2aebf864e0@5","shortId":"4JJLgeoc@5","title":"XML - Tags, Elements, Content, and Attributes"},        +
         {"id":"d8c4a5bc-1a60-483c-8aba-5f634570ca25@8","shortId":"2MSlvBpg@8","title":"XML - Well-Formed and Valid Documents"},                +
         {"id":"999d07f7-47d9-42ad-bba7-e8837faf19f0@4","shortId":"mZ0H90fZ@4","title":"Xml0100 Writing XML Review"},                           +
         {"id":"5f200dfa-c590-4d97-8d27-e50dc761ec04@2","shortId":"XyAN-sWQ@2","title":"Xml0110 Transforming XML Review"},                      +
         {"id":"130bae60-ef72-4fcf-a313-4844f703c8f4@2","shortId":"EwuuYO9y@2","title":"Xml0120 Validating XML Review"},                        +
         {"id":"aaf7da27-4a94-4fef-a5d1-65b094eb82ae@1","shortId":"qvfaJ0qU@1","title":"Json0110: Preface to JSON"},                            +
         {"id":"497498bd-cf29-4662-9c01-0815f36c8ccb@1","shortId":"SXSYvc8p@1","title":"Json0120: What is JSON?"},                              +
         {"id":"3432a6de-ed5b-49df-b6f5-f4717f6f2faa@6","shortId":"NDKm3u1b@6","title":"Json0130: JSON and JavaScript"},                        +
         {"id":"208099c2-2175-4927-a50e-59d3d3bf7fcc@1","shortId":"IICZwiF1@1","title":"Json0140-Calling External JavaScript Functions"}]},     +
     {"id":"subcol","shortId":"subcol","title":"Flex", "contents":[                                                                             +
         {"id":"a783d6c7-2674-4425-be32-5f788a927ec1@1","shortId":"p4PWxyZ0@1","title":"XML - Namespaces - Flex 3"},                            +
         {"id":"f9aca92e-f01c-4e71-bdbf-249e34880ca8@1","shortId":"-aypLvAc@1","title":"XML - Namespaces - Flex 4"},                            +
         {"id":"ecffe202-d6c2-4bf0-9a9a-6045dc65fd0e@2","shortId":"7P_iAtbC@2","title":"The Default Application Container - Flex 3 and Flex 4"},+
         {"id":"693a6f0a-5b8c-4bcd-9e2d-0b979c697d3d@1","shortId":"aTpvCluM@1","title":"Using Flex 3 in a Flex 4 World"},                       +
         {"id":"a9375fd0-5b84-49a2-b83c-db226e008140@1","shortId":"qTdf0FuE@1","title":"Handling Slider Change Events in Flex 3 and Flex 4"},   +
         {"id":"1b75e7ce-22e5-4807-9ea4-63a074865f36@2","shortId":"G3XnziLl@2","title":"Flex Resources"}]}]}
(1 row)
```

</details>

**Comment by pumazi** [comment] 2017-07-25 21:32
The 'tree' is not empty as in an empty string (`''`). It would be `null`. And that's the the error.

**Comment by pumazi** [comment] 2017-07-25 21:33
```repository=# do language plpythonu
repository-# $$
repository$# import io
repository$# import plpy
repository$# from cnxarchive.transforms.resolvers import CnxmlToHtmlReferenceResolver
repository$# resolver = CnxmlToHtmlReferenceResolver(io.BytesIO('<html></html>'), plpy)
repository$# page_uuid, page_version = ('28fbff54-eeca-4a9d-87fd-e3c1661e4daf', '2')
repository$# book_uuid, book_version = ('d394d2b3-8ce0-4182-9631-18cf68be920c', '18.6')
repository$# result = resolver.get_page_ident_hash(page_uuid, page_version, book_uuid, book_version)
repository$# plpy.info(result)
repository$# $$;
INFO:  ('d394d2b3-8ce0-4182-9631-18cf68be920c', 'd394d2b3-8ce0-4182-9631-18cf68be920c@18.6:28fbff54-eeca-4a9d-87fd-e3c1661e4daf@2')```

I'd suggest someone take the above snippet and use the actual content rather than my simplified `<html></html>`. That may help to debug the issue further.

**Comment by karenc** [comment] 2017-07-25 22:25
I used the above code and created a function called `karen`, this is the error:

```
cnxarchive=# select karen();                                                   
ERROR:  spiexceptions.UndefinedFunction: function tree_to_json(uuid, text, boolean) does not exist                                                                   
LINE 1: SELECT tree_to_json($1, $2, FALSE)::json                               
               ^                                                               
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.                                                             
QUERY:  SELECT tree_to_json($1, $2, FALSE)::json                               
CONTEXT:  Traceback (most recent call last):                                   
  PL/Python function "karen", line 664, in <module>                            
    result = resolver.get_page_ident_hash(page_uuid, page_version, book_uuid, book_version)                                                                          
  PL/Python function "karen", line 351, in get_page_ident_hash                 
PL/Python function "karen"
```

How was this working? O_O  Anyway, I made this change:

```diff
diff --git a/cnxarchive/transforms/resolvers.py b/cnxarchive/transforms/resolvers.py
index cad1af1..ea2cbb3 100644
--- a/cnxarchive/transforms/resolvers.py
+++ b/cnxarchive/transforms/resolvers.py
@@ -349,7 +349,7 @@ class CnxmlToHtmlReferenceResolver(BaseReferenceResolver):
         from cnxepub import flatten_tree_to_ident_hashes  # XXX
         from ..utils import join_ident_hash  # XXX
         plan = self.plpy.prepare(
-            'SELECT tree_to_json($1, $2, FALSE)::json', ('uuid', 'text'))
+            'SELECT tree_to_json($1, $2, FALSE)::json', ('text', 'text'))
         tree = self.plpy.execute(
             plan, (book_uuid, book_version))[0]['tree_to_json']
         if isinstance(tree, basestring):
```

Next error I got:

```
cnxarchive=# select karen();
ERROR:  TypeError: argument of type 'NoneType' is not iterable
CONTEXT:  Traceback (most recent call last):
  PL/Python function "karen", line 664, in <module>
    result = resolver.get_page_ident_hash(page_uuid, page_version, book_uuid, book_version)
  PL/Python function "karen", line 356, in get_page_ident_hash
  PL/Python function "karen", line 149, in flatten_tree_to_ident_hashes
PL/Python function "karen"
```

which is expected because I don't have anything in the database.  I'm waiting for the database dump to finish.  Hopefully will reproduce the error locally.

**Comment by karenc** [comment] 2017-07-26 14:59
I got the qa database and tried to transform the module locally:

```
cnxarchive=# create or replace function karen() returns void as $$
             
from cnxarchive.transforms import produce_html_for_module
import plpy  
produce_html_for_module(plpy, 101136, source_filename='index.cnxml', destination_filenames=('index.cnxml.html',))
$$ language plpythonu;
CREATE FUNCTION
cnxarchive=# delete from module_files where module_ident = 101136 and filename = 'index.cnxml.html';
DELETE 1
cnxarchive=# select karen();
INFO:  produce {}->{} for module_ident = {}
 karen
-------

(1 row)

cnxarchive=# select * from module_files where module_ident = 101136;
 module_ident | fileid |     filename
--------------+--------+------------------
       101136 | 564435 | index.cnxml
       101136 | 927422 | index.cnxml.html
(2 rows)

cnxarchive=# select encode(file, 'escape') from files where fileid = 927422;
```

The transform was successful.  

----

I tried running [retransform_cnxml_html.sql](https://github.com/Connexions/devops/blob/master/scripts/retransform_cnxml_html.sql) and that completed successfully as well.

**Comment by karenc** [comment] 2017-07-26 16:09
I tried doing something that will trigger a similar error and this is what I find:

```
>>> tree = '{"id":"d394d2b3-8ce0-4182-9631-18cf68be920c@18.6","shortId":"05TSs4zg@18.6","title":"Introduction to XML", "contents":[\n    {"id":"subcol","shortId":"subcol","title":"Preface", "contents":[\n        {"id":"28fbff54-eeca-4a9d-87fd-e3c1661e4daf@2","shortId":"KPv_VO7K@2","title":"Preface, Introduction to XML"}]},\n    {"id":"subcol","shortId":"subcol","title":"ITSE1356", "contents":[\n        {"id":"8e1cc59a-71f5-455f-a778-312de12c440f@5","shortId":"jhzFmnH1@5","title":"A Brief Introduction to XML"},\n        {"id":"e0924b81-ea1c-42a8-823d-2b2aebf864e0@5","shortId":"4JJLgeoc@5","title":"XML - Tags, Elements, Content, and Attributes"},\n        {"id":"d8c4a5bc-1a60-483c-8aba-5f634570ca25@8","shortId":"2MSlvBpg@8","title":"XML - Well-Formed and Valid Documents"},\n        {"id":"999d07f7-47d9-42ad-bba7-e8837faf19f0@4","shortId":"mZ0H90fZ@4","title":"Xml0100 Writing XML Review"},\n        {"id":"5f200dfa-c590-4d97-8d27-e50dc761ec04@2","shortId":"XyAN-sWQ@2","title":"Xml0110 Transforming XML Review"},\n        {"id":"130bae60-ef72-4fcf-a313-4844f703c8f4@2","shortId":"EwuuYO9y@2","title":"Xml0120 Validating XML Review"},\n        {"id":"aaf7da27-4a94-4fef-a5d1-65b094eb82ae@1","shortId":"qvfaJ0qU@1","title":"Json0110: Preface to JSON"},\n        {"id":"497498bd-cf29-4662-9c01-0815f36c8ccb@1","shortId":"SXSYvc8p@1","title":"Json0120: What is JSON?"},\n        {"id":"3432a6de-ed5b-49df-b6f5-f4717f6f2faa@6","shortId":"NDKm3u1b@6","title":"Json0130: JSON and JavaScript"},\n        {"id":"208099c2-2175-4927-a50e-59d3d3bf7fcc@1","shortId":"IICZwiF1@1","title":"Json0140-Calling External JavaScript Functions"}]},\n    {"id":"subcol","shortId":"subcol","title":"Flex", "contents":[\n        {"id":"a783d6c7-2674-4425-be32-5f788a927ec1@1","shortId":"p4PWxyZ0@1","title":"XML - Namespaces - Flex 3"},\n        {"id":"f9aca92e-f01c-4e71-bdbf-249e34880ca8@1","shortId":"-aypLvAc@1","title":"XML - Namespaces - Flex 4"},\n        {"id":"ecffe202-d6c2-4bf0-9a9a-6045dc65fd0e@2","shortId":"7P_iAtbC@2","title":"The Default Application Container - Flex 3 and Flex 4"},\n        {"id":"693a6f0a-5b8c-4bcd-9e2d-0b979c697d3d@1","shortId":"aTpvCluM@1","title":"Using Flex 3 in a Flex 4 World"},\n        {"id":"a9375fd0-5b84-49a2-b83c-db226e008140@1","shortId":"qTdf0FuE@1","title":"Handling Slider Change Events in Flex 3 and Flex 4"},\n        {"id":"1b75e7ce-22e5-4807-9ea4-63a074865f36@2","shortId":"G3XnziLl@2","title":"Flex Resources"}]}]}'
>>> list(flatten_tree_to_ident_hashes(tree))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "cnxepub/models.py", line 152, in flatten_tree_to_ident_hashes
    if tree['id'] != lucent_id:
TypeError: string indices must be integers, not str
>>> list(flatten_tree_to_ident_hashes(json.loads(tree)))
[u'd394d2b3-8ce0-4182-9631-18cf68be920c@18.6', u'28fbff54-eeca-4a9d-87fd-e3c1661e4daf@2', u'8e1cc59a-71f5-455f-a778-312de12c440f@5', u'e0924b81-ea1c-42a8-823d-2b2aebf864e0@5', u'd8c4a5bc-1a60-483c-8aba-5f634570ca25@8', u'999d07f7-47d9-42ad-bba7-e8837faf19f0@4', u'5f200dfa-c590-4d97-8d27-e50dc761ec04@2', u'130bae60-ef72-4fcf-a313-4844f703c8f4@2', u'aaf7da27-4a94-4fef-a5d1-65b094eb82ae@1', u'497498bd-cf29-4662-9c01-0815f36c8ccb@1', u'3432a6de-ed5b-49df-b6f5-f4717f6f2faa@6', u'208099c2-2175-4927-a50e-59d3d3bf7fcc@1', u'a783d6c7-2674-4425-be32-5f788a927ec1@1', u'f9aca92e-f01c-4e71-bdbf-249e34880ca8@1', u'ecffe202-d6c2-4bf0-9a9a-6045dc65fd0e@2', u'693a6f0a-5b8c-4bcd-9e2d-0b979c697d3d@1', u'a9375fd0-5b84-49a2-b83c-db226e008140@1', u'1b75e7ce-22e5-4807-9ea4-63a074865f36@2']
>>> list(flatten_tree_to_ident_hashes(''))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "cnxepub/models.py", line 160, in flatten_tree_to_ident_hashes
    yield item['id']
TypeError: string indices must be integers, not str
>>> list(flatten_tree_to_ident_hashes([]))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "cnxepub/models.py", line 160, in flatten_tree_to_ident_hashes
    yield item['id']
TypeError: list indices must be integers, not str
>>> list(flatten_tree_to_ident_hashes({}))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "cnxepub/models.py", line 160, in flatten_tree_to_ident_hashes
    yield item['id']
KeyError: 'id'
```

I think the first case, the json string, is most similar to the original traceback:

```
psql:retransform_cnxml_html.sql:5: ERROR:  TypeError: string indices must be integers, not str
CONTEXT:  Traceback (most recent call last):
  PL/Python function "add_module_file", line 3, in <module>
    return add_module_file(plpy, TD)
  PL/Python function "add_module_file", line 727, in add_module_file
  PL/Python function "add_module_file", line 218, in produce_html_for_module
  PL/Python function "add_module_file", line 293, in produce_transformed_file
  PL/Python function "add_module_file", line 254, in resolve_urls
  PL/Python function "add_module_file", line 247, in __call__
  PL/Python function "add_module_file", line 445, in fix_anchor_references
  PL/Python function "add_module_file", line 354, in get_page_ident_hash
  PL/Python function "add_module_file", line 151, in flatten_tree_to_ident_hashes
PL/Python function "add_module_file"
```

**Comment by karenc** [comment] 2017-07-26 16:59
Transforming just that module on QA worked fine:

```
karen@qa00:~$ psql repository <retransform_cnxml_html.sql
              now
-------------------------------
 2017-07-26 11:57:01.844682-05
(1 row)       
              
BEGIN         
SELECT 1      
DELETE 61910  
INFO:  produce cnxml->html for module_ident = 101136
INFO:  produce {}->{} for module_ident = {}
INSERT 0 1    
   Table "pg_temp_13.index_cnxml"
    Column    |  Type   | Modifiers
--------------+---------+-----------
 module_ident | integer | 
 fileid       | integer | 
 filename     | text    | 

COMMIT
```

**Comment by kerwinso** [comment] 2017-07-26 19:26
After Karen's latest re-transform, this appears to be fixed on https://qa.cnx.org/contents/P0QbZjyW@1/How-Economies-Can-Be-Organized:

![image](https://user-images.githubusercontent.com/11298165/28639571-4b36e782-720e-11e7-841c-c14110e426db.png)

**Comment by karenc** [comment] 2017-07-26 19:59
I reran transform on QA and it completed successfully:

```
karen@qa00:~$ psql repository <retransform_cnxml_html.sql
...
INFO:  produce cnxml->html for module_ident = 8561
INFO:  produce {}->{} for module_ident = {}
INFO:  produce cnxml->html for module_ident = 8560
INFO:  produce {}->{} for module_ident = {}
INFO:  produce cnxml->html for module_ident = 8515
INFO:  produce {}->{} for module_ident = {}
INSERT 0 30955
   Table "pg_temp_12.index_cnxml"
    Column    |  Type   | Modifiers
--------------+---------+-----------
 module_ident | integer |
 fileid       | integer |
 filename     | text    |

COMMIT
```

**Comment by philschatz** [comment] 2017-07-26 20:23
Re-running the script succeeded on QA (not sure how to fix the bug since @karenc was unable to reproduce it locally or on QA). So putting it back into testing.

**Note:** This does mean that anyone who runs the script will need to check the exit status code (or the `nohup.log` file to see if Ross' script actually succeeded or if it failed)

**Comment by philschatz** [comment] 2017-07-26 20:26
Grumble, I have a feeling varnish cached the page content. @karenc or @pumazi could you clear varnishes cache?

**Comment by kerwinso** [comment] 2017-07-26 20:46
Closing this as fixed, see my brilliantly insightful comment here:
https://github.com/Connexions/cnx-recipes/issues/295#issuecomment-318156838

**Closed by kerwinso** 2017-07-26 20:46 UTC
