### ISSUE TITLE
TEA Books => Cannot edit chapter or module titles in the Gateway

### ISSUE THREAD

**Issue by oscryan** [Connexions/cnx-recipes#359] opened 2017-11-16 21:08 UTC
There is no visible way to edit a chapter or module title within the TEG.
<img width="1096" alt="screen shot 2017-11-16 at 3 06 59 pm" src="https://user-images.githubusercontent.com/1895432/32915886-061c24a2-cae0-11e7-9f61-b2c96460c467.png">
<img width="1094" alt="screen shot 2017-11-16 at 3 06 51 pm" src="https://user-images.githubusercontent.com/1895432/32915887-062e2ef4-cae0-11e7-88a6-76d99635e31b.png">
<img width="1096" alt="screen shot 2017-11-16 at 3 06 33 pm" src="https://user-images.githubusercontent.com/1895432/32915888-063cc04a-cae0-11e7-9252-236905dd6cba.png">

**Comment by nyxer95** [comment] 2017-11-16 21:25
Cannot edit the chapter title "13 F Distribution and One-way Anova".

Cannot edit the module title "13.1 One-way ANOVA".

**Comment by elenafournier** [comment] 2017-11-29 00:13
Hi there,
Based on the last 2 screenshots, the user is a Content Editor, which by default should be able to edit titles of module or chapters. This can be done by going to the Overview Tab. Could you please verify that going there allows you to edit the resource?  Content Creators should have this capability as well.

**Comment by Stackblocks** [comment] 2017-11-29 19:19
Ryan & I both went back in and attempted to edit the title for chapter 13 in the Overview section. Both of us were able to edit the content (in this instance correcting the capitalization on `One-Way Anova`, but the changes did not stick when the save button was pressed. This was attempted with `Pending - needs review` selected, and unselected. Same results each time.

![image](https://user-images.githubusercontent.com/12678235/33394188-2d94c102-d507-11e7-81fc-700c6396026e.png)
![image](https://user-images.githubusercontent.com/12678235/33394201-30eca4f0-d507-11e7-94ac-b5af3a56a45e.png)

**Comment by elenafournier** [comment] 2017-11-29 19:53
Thanks for letting me know.  We will take a look at it. 


Elena Fournier
Trinity Education Group
efournier@tegtech.io
(410) 531-7555 ext. 709
(877) 858-3865 ext. 709

**Comment by elenafournier** [comment] 2017-11-29 20:25
We could not reproduce the issue. Anyway, I just looked in prod and it appears to have reflected the change.  Please let me know if I am looking at the wrong item here (screenshot)
![image](https://user-images.githubusercontent.com/33755030/33397374-725df242-d519-11e7-8808-62caf6671549.png)

**Comment by Stackblocks** [comment] 2017-11-29 20:28
It looks like you’re looking at the title of module 13.1, as opposed to the chapter title "13 F Distribution and One-way Anova" visible here: https://www.texasgateway.org/book/tea-statistics.

Alan Cooke
QA Specialist
OpenStax, Rice University

On November29,2017 at 2:25:19 PM, elenafournier (notifications@github.com) wrote:

We could not reproduce the issue. Anyway, I just looked in prod and it appears to have reflected the change. Please let me know if I am looking at the wrong item here (screenshot)

**Comment by elenafournier** [comment] 2017-11-29 20:43
Thanks for clarifying.  I went ahead and edited the chapter title and it worked fine.  One thing I noticed and which our developer also pointed out when he tested module 13.1 is that it is missing a desciption.  I went ahead and added that because it is required. Not sure if that made a difference.  I know I get prompted to add a description when saving. 
![image](https://user-images.githubusercontent.com/33755030/33398123-e4ac22e0-d51b-11e7-842c-4eb4e8a52989.png)

![image](https://user-images.githubusercontent.com/33755030/33398149-f89a0e34-d51b-11e7-9618-d923bafe6396.png)

**Comment by Stackblocks** [comment] 2017-11-29 20:47
I think I see the issue, we were attempting to edit from the book level, while the change you’ve included a screenshot of was done at the binder level directly. I’ll pass that information along. Thanks for your help!

Alan Cooke
QA Specialist
OpenStax, Rice University

On November29,2017 at 2:43:36 PM, elenafournier (notifications@github.com) wrote:

Thanks for clarifying. I went ahead and edited the chapter title and it worked fine. One thing I noticed and which our developer also pointed out when he tested module 13.1 is that it is missing a desciption. I went ahead and added that because it is required. Not sure if that made a difference. I know I get prompted to add a description when saving.

**Comment by Stackblocks** [comment] 2017-11-29 20:48
Elena was able to edit the chapter title by navigating to the the "Binder" of the same name and editing the title there. She was prompted to include a summary and did so, and the change took when the save button was pressed. Closing the issue as resolved.

**Closed by Stackblocks** 2017-11-29 20:48 UTC
Labels: priority:high, problem.type:gateway-issue
