### ISSUE TITLE
TEA => AP Biology issues for review

### ISSUE THREAD

**Issue by Stackblocks** [Connexions/cnx-recipes#318] opened 2017-08-21 01:16 UTC
# Scenario

This issue will collect the issues in the Final Delivery content for AP Biology which can be spun out into separate issues as necessary.

### 1. Book-wide -- Learning objectives missing.
(resolved as of 2017-08-18, pending re-delivery)

**2017-09-12 Status:** ✅ 

### 2. [Ch.12](https://stg.texasgateway.org/resource/science-practice-challenge-questions-9?book=280771) -- Science Practice Challenge Questions.
![image](https://user-images.githubusercontent.com/12678235/29500165-a7cbec20-85e3-11e7-949b-bafb4fcb8fe4.png)

**2017-09-12 Status:** ✅ 

### 3. [Ch. 16.2](https://stg.texasgateway.org/resource/162-prokaryotic-gene-regulation?book=334466) -- Italics missing from title
![image](https://user-images.githubusercontent.com/12678235/29531387-f5b0746c-866d-11e7-8b07-7b0d7433e9ff.png)

**2017-09-12 Status:** ✅  (Math in title display issue common across all books, TEG issue)

### 4. [Ch. 16 Test Prep](https://stg.texasgateway.org/resource/test-prep-ap%C2%AE%C2%A0courses-14?book=334466) -- Floating text next to image
![image](https://user-images.githubusercontent.com/12678235/29533235-86127a7a-8676-11e7-8486-b62bd74216d8.png)
Also present on tea.cnx, may be a line-break issue.

**2017-09-12 Status:** ✅ 

### 5. [Ch. 17.1](https://stg.texasgateway.org/resource/171-biotechnology?book=334466) -- Repeating Image
![image](https://user-images.githubusercontent.com/12678235/29534450-b92ca098-867b-11e7-8a27-48c0b1b3e8c0.png)
![image](https://user-images.githubusercontent.com/12678235/29534463-c448c452-867b-11e7-8b68-55666d32a76b.png)
Also present on tea.cnx.org

**2017-09-12 Status:** ⚠️

### 6. [Ch. 17.4](https://stg.texasgateway.org/resource/174-applying-genomics?book=334466) -- Double `a.` in list.
![image](https://user-images.githubusercontent.com/12678235/29534552-0ad3c6f6-867c-11e7-932d-5ecf8b4c5238.png)

**2017-09-12 Status:** ✅ 

### 7. [Ch. 17 Review](https://stg.texasgateway.org/resource/review-questions-49?book=334466) -- More option letter doubling.
![image](https://user-images.githubusercontent.com/12678235/29534625-476d811a-867c-11e7-8ba5-ebfb7679bcec.png)

**2017-09-12 Status:** ✅ 

Same again in Critical Thinking Questions.
![image](https://user-images.githubusercontent.com/12678235/29534748-b93db80a-867c-11e7-8be1-2a1d10ca2de7.png)

**2017-09-12 Status:** ✅  ⚠️  ❌

### 8. [33.1](https://stg.texasgateway.org/resource/331-innate-immune-response?book=334466) -- Misplaced line-breaks
![image](https://user-images.githubusercontent.com/12678235/29584335-06bbce7e-8749-11e7-8d48-f641d4e46ef1.png)
![image](https://user-images.githubusercontent.com/12678235/29584374-24aa2246-8749-11e7-920a-05c4beced776.png)

**2017-09-12 Status:** ✅ 

### 9. [38.1](https://stg.texasgateway.org/resource/381-biodiversity-crisis?book=282466) -- Stray dashes
![image](https://user-images.githubusercontent.com/12678235/29639097-3287fbdc-881f-11e7-81f4-e880e64f35e2.png)

**2017-09-12 Status:** ✅ 

# Environment:

- **Instance**: Gateway Staging
- **OS**: macOS
- **Browser**: Chrome

**Comment by tomjw64** [comment] 2017-08-21 15:42
For 2) Because we are using the `display: flex` attribute to add list-like indentation to each item, and because there is no wrapping within the `li` element of the list, the `strong` element and the text are taking block display properties. Two solutions are possible: Revert back to using the `float` property, but lose the indentation and preserve leading whitespace, or write a recipe change that will add internal wrapping on `li` elements for TEA books.

**Comment by tomjw64** [comment] 2017-08-22 21:20
6 & 7) Letters are added by CSS by default, but they already existed in content. The letters in content should be removed by @oscryan if possible.

**Comment by tomjw64** [comment] 2017-08-22 21:22
5. Content contains both a figure with the said image (referencing an internal resource) as well as an exercise with the said image (but this time using a full url link to an external resource). Content team should decide which to keep.

**Comment by oscryan** [comment] 2017-08-22 21:22
6 & 7 ) yeah I did all of those duplicate list letters I think

**Comment by philschatz** [comment] 2017-08-23 18:33
3. It looks like the gateway is stripping the default browser styling of `<em>` tag out but I am not sure. Unfortunately, the TEG staging server was reset so the links are no longer clickable

![image](https://user-images.githubusercontent.com/253202/29632136-feff5aa8-880f-11e7-9c0d-4eb0aaa19e2b.png)

**Comment by helenemccarron** [comment] 2017-08-23 18:45
#8  looks like the characters `and/or` somehow cause the line to break, might be a content issue

**Comment by tomjw64** [comment] 2017-08-23 18:46
8 is caused by a `data-type="newline"` element with a `br` in content, can be fixed by restyling this type of element

**Comment by oscryan** [comment] 2017-08-23 18:50
@tomjw64 would that affect cnxml elements '<newline/>'? cause we need those

**Comment by philschatz** [comment] 2017-08-23 18:54
@oscryan is the `<cnx:newline/>` element needed in the content? It seems like it was added mid-sentence. Also, probably not as important as the other items?

**Comment by oscryan** [comment] 2017-08-23 18:55
@philschatz yes, it is needed in the content. Just not here.

**Comment by Stackblocks** [comment] 2017-08-23 19:00
No.3 spun off into issue #323

**Comment by philschatz** [comment] 2017-08-29 17:32
Another round of testing. Seems the list styling is fixed. Some of the other issuese might be gone with a new reimport (they were content problems)

2 ) 
![image](https://user-images.githubusercontent.com/253202/29834332-858160ac-8cbc-11e7-85f2-9afc081119e9.png)

3 ) No change. This is a bug in the importer. see #323
4 ) No change. This is a (possibly fixed) content bug. Need to reimport books
5 ) No change. Image is still repeating. Needs a content fix or a recipe fix. /cc @helenemccarron 
6 ) No change. This is a (possibly fixed) content bug. Need to reimport books
7 ) The exercises are missing!
8 ) No change. Wontfix. It's a content update but no biggie
9 ) No change. It's a content thing

**Comment by oscryan** [comment] 2017-08-29 19:08
4) is fixed. It was on Exercises, not cnx.
5) is fixed. One image was on Exercises, one on cnx. I deleted the one on cnx.
6) is fixed.
7) is fixed. all of these exercises were on cnx, not pulled from Tutor. Are we sure it baked?
8) is fixed.
9) is fixed. That exercise was duplicated, someone tried to comment it out, and an extra comment end was showing.

**Closed** 2017-09-12 20:37 UTC
Labels: env:gateway, TEA
