### ISSUE TITLE
Business Ethics - Index entries in Webview

### ISSUE THREAD

**Issue by mwest-WWprod** [Connexions/cnx-recipes#486] opened 2018-07-19 22:29 UTC
content01
GLOBAL - Webview

Index entries are missing when a term has multiple entries (compare C and E listings in Webview to PDF). 

Webview
![index webview](https://user-images.githubusercontent.com/19212926/42973555-83102956-8b81-11e8-8e34-4930adada203.png)

PDF
![index pdf](https://user-images.githubusercontent.com/19212926/42973559-869b9cae-8b81-11e8-9d0f-359c498a0f43.png)

**Comment by openstaxalina** [comment] 2018-08-03 15:15
@lwtchu check if the occurrences are in the same module.

**Comment by openstaxalina** [comment] 2018-08-03 15:21
The second occurrence of each term is in the Key Terms section of the chapter.  
We do not currently have the ability to link to the Key Terms from the Index.  However, since users can search the book via a search tool in webview, the impact of this is minimal.
**Decision: Will not fix; will evaluate for future improvement.**

**Comment by lwtchu** [comment] 2018-08-03 15:57
TO DO: Investigate if the word is indexed twice in the section, will it link twice.

**Comment by lwtchu** [comment] 2018-08-15 21:08
Confirmed, if word is indexed twice in the section, it will link twice.
![screen shot 2018-08-15 at 4 07 45 pm](https://user-images.githubusercontent.com/11299125/44173396-64716080-a0a5-11e8-8dbd-8af85d7c6575.png)
https://devb.cnx.org/contents/WUj6TfJ0@9.2:RaYySq2K@9.2/Index

**Comment by openstaxalina** [comment] 2018-08-15 21:10
This is the desired behavior, since each link points to the specific place in the module where the word appears.  Closing this issue.

**Closed by openstaxalina** 2018-08-15 21:10 UTC
Labels: book:business.ethics, env:staging, prio:low, problem.type:webview-issue, type:enhancement
