### ISSUE TITLE
Change `os-` class prefix to `ox-`

### ISSUE THREAD

**Issue by philschatz** [Connexions/cnx-recipes#123] opened 2016-12-15 01:42 UTC
This makes it clearer that these are **O**pensta**X** classes and not OpenSource or OperatingSystem. Also lines up with other cases where we need to abbreviate OpenStax.

**Comment by openstaxalina** [comment] 2018-03-16 14:27
Duplicate of #271 - closing.

**Closed by openstaxalina** 2018-03-16 14:27 UTC
