### ISSUE TITLE
TEA => Missing Content on the Gateway

### ISSUE THREAD

**Issue by Stackblocks** [Connexions/cnx-recipes#315] opened 2017-08-17 20:23 UTC
# Description

This issue collects the various missing content issues in one place for easy reference.

# Reproducibility Details

- **Impact area**: Gateway Staging
- **User**: openstax@texasgateway.org
- **URL / Location**: stg.texasgateway.org
- **How many times were you able to reproduce the issue?** n/a

### 1. [HS Stats 11.4](https://stg.texasgateway.org/resource/114-test-homogeneity?book=261661) -- Missing introductory paragraph.
![image](https://user-images.githubusercontent.com/12678235/29431137-81303d5c-835c-11e7-9082-8c0dd14528ab.png)

### 2. [HS Stats 7.3](https://stg.texasgateway.org/resource/73-using-central-limit-theorem?book=261661) -- Missing introductory paragraph
![image](https://user-images.githubusercontent.com/12678235/29434390-71facfda-8368-11e7-9dc7-8ecadcb743a7.png)

### 3. [HS Physics Book-Wide](https://stg.texasgateway.org/resource/11-physics-definitions-and-applications?book=256821) -- Section Key Terms missing
![image](https://user-images.githubusercontent.com/12678235/29431794-d9c204ee-835e-11e7-932e-31374a370b77.png)
![image](https://user-images.githubusercontent.com/12678235/29420465-a630e9e6-8337-11e7-8ea1-003c01ceccc0.png)

This is not the case in the following modules: [18.3](https://stg.texasgateway.org/resource/183-electric-field?book=256821) and [18.4](https://stg.texasgateway.org/resource/184-electric-potential?book=256821) where the section key terms are present under an out-of-place h3:

![image](https://user-images.githubusercontent.com/12678235/29436743-b533a466-8372-11e7-851b-fd781f67eefd.png)
![image](https://user-images.githubusercontent.com/12678235/29436766-dcd3708c-8372-11e7-9c57-7ac99998da33.png)

### 4. [HS Physics Ch. 3.2](https://stg.texasgateway.org/resource/32-representing-acceleration-equations-and-graphs?book=256821) -- Constant Acceleration practice problems missing
![image](https://user-images.githubusercontent.com/12678235/29431964-777e91b6-835f-11e7-96ff-c84b7bc307fa.png)

### 5. [HS Physics Ch. 18.1](https://stg.texasgateway.org/resource/181-electrical-charges-conservation-charge-and-transfer-charge?book=256821) -- Transfer and Separation of Charge practice problems missing
![image](https://user-images.githubusercontent.com/12678235/29433533-2b6f3702-8365-11e7-80a9-890a9dfd968f.png)

### 6. [HS Stats Ch.5.1](https://stg.texasgateway.org/resource/51-continuous-probability-functions?book=261661) Introductory Paragraph Missing
![image](https://user-images.githubusercontent.com/12678235/29436046-53c7e5dc-836f-11e7-9c57-62729df591eb.png)

### 7. [HS Physics 12.1](https://stg.texasgateway.org/resource/121-zeroth-law-thermodynamics-thermal-equilibrium?book=256821) -- Most of the content is missing.
![image](https://user-images.githubusercontent.com/12678235/29436083-965520a4-836f-11e7-8033-9a77d9476009.png)

### 8. [AP Physics 2 Ch. 2.7](https://stg.texasgateway.org/resource/27-energy-stored-capacitors?book=293891) -- Post learning objective content missing.
![image](https://user-images.githubusercontent.com/12678235/29502205-e4da6924-85f3-11e7-9981-d6143dbec886.png)

# Environment:

- **OS**: macOS
- **Browser**: Chrome

**Comment by tomjw64** [comment] 2017-08-21 19:00
1 & 2) Both of those p elements have `id="delete_me"`. I've checked, and it has `"delete_me"` in the id even in the raw file. What might be happening, is that if more than one item has `id="delete_me"`, it might be stripped by TEG (the `p` elements make it through EPUB generation with the id)

**Comment by tomjw64** [comment] 2017-08-21 19:07
4) Can't reproduce?

**Comment by tomjw64** [comment] 2017-08-21 19:08
3) Key terms are in a `section` element with no header. I can resolve this by moving it into the section learning objectives section

**Comment by tomjw64** [comment] 2017-08-21 20:14
7. That section in HS Physics does not seem to have the same `section` format we are using everywhere else in the book, so the Gateway is not finding a `section > title` and not accepting the content.

**Comment by oscryan** [comment] 2017-08-22 01:12
there is no difference between the structure (or class! it has a class!) of the opening content in 12.1 and the opening content in the rest of the modules in chapter 12. It's a section tag with learning objective notes in it, and the section tag has class="section-opener". I can't figure out why it would be treated differently by the css or the gateway.

**Comment by oscryan** [comment] 2017-08-22 01:21
I have changed the Stats 5.1 intro paragraph's ID, so if the duplicate id was the problem it should now be fixed

**Comment by oscryan** [comment] 2017-08-22 01:29
@tomjw64 I hypothesize that the Key Terms of all but 2 modules were missing on this particular content check because the initial Gateway migration was still of phase I content; remember I had to migrate HS Physics a fourth time, and all the key terms should show up next time the Gateway gets HS Physics content from tea.cnx.org. Don't panic too hard about moving things under h3s yet

**Comment by oscryan** [comment] 2017-08-22 15:14
wrapped the middle content in a section tag for HS Phys 12.1

**Comment by tomjw64** [comment] 2017-08-22 15:20
4 & 5. After taking a closer look at those pages/modules of the book. It appears that those modules had two separate Practice Problems sections. The Gateway seems to be unable to handle two navigation sections of the same name or something. What ends up happening is once the second Practice Problems is reached, the Gateway replaces the first instance of Practice Problems with the second one that it found (In each case, the second Practice Problems section is where the first should have been, but the first one is nowhere to be found!)

**Comment by oscryan** [comment] 2017-08-22 16:01
...unwrapped it

**Comment by rfreedholm** [comment] 2017-08-28 21:41
For #8 in this list, our developer has reported that the issue is that the section markup has no h3 as a title and the importer requires one. Can you add an h3 to the markup?

**Comment by oscryan** [comment] 2017-08-28 23:18
for #8 added redundant title to wrapped middle `<section>`. Published, regenerating ap phys 2

**Closed** 2017-09-25 22:55 UTC
Labels: env:gateway, problem.type:gateway-issue, TEA
